# _config.yml
plugins:
  - jekyll-remote-theme

remote_theme: andrewbanchich/forty-jekyll-theme

# site settings
title: TheraText Solutions
subtitle: Notetaking and Submission Software
email: theratext.solutions@gmail.com
description: Radically simplifying the notetaking process for care providers in rural areas
baseurl: "" # Leave empty for custom domain root
url: "https://www.theratext.site" # Use domain name
author:
street_address: Discovery Hall 2502 19th Ave
city: Kearney
state: NE
zip_code: 68849
country: United States of America
phone: (720) 470 8062

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/alexisbernt
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
